# Generated by Django 5.2.1 on 2025-06-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_games',
            field=models.ManyToManyField(blank=True, related_name='cart_users', to='store.game'),
        ),
    ]
